
import './globals.css'

export const metadata = {
  title: 'My Todo App',
  description: 'Generated by Rehaan Ansari',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
